### ISSUE TITLE
Error in /c2v while generating thumbnail 

### ISSUE THREAD

**Issue by hemanth-narra** [prxpostern/URLtoTG001#8]
Machine: Ubuntu 20.04,  AMD, VPS
```
2023-01-11 09:43:47,512 - helpers.vconverter - INFO - status: True
2023-01-11 09:43:53,513 - helpers.ffprobe - DEBUG - ['ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '/home/ubuntu/URLtoTG001/downloads/kristin_29.mp4']
2023-01-11 09:43:53,521 - pyrogram.dispatcher - ERROR - [Errno 2] No such file or directory: 'ffprobe'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/URLtoTG001/plugins/funcs.py", line 106, in to_video1
    await to_video2(client , u)
  File "/home/ubuntu/URLtoTG001/helpers/vconverter.py", line 118, in to_video2
    thumbnail, duration, width, height = await thumb_creator(file_path)
  File "/home/ubuntu/URLtoTG001/helpers/thumbnail_video.py", line 20, in thumb_creator
    probe = await stream_creator(filepath)
  File "/home/ubuntu/URLtoTG001/helpers/ffprobe.py", line 31, in stream_creator
    process = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'
```

**Comment by prxpostern** [comment]
hi. did you install ffmpeg on your vps ?

apt-get install ffmpeg

**Comment by hemanth-narra** [comment]
No, I just did that. 
and working fine now.  Thank you.

**Comment by prxpostern** [comment]
i recommend you to use Docker.
docker is better.

**Comment by hemanth-narra** [comment]
okay
